// GENERATED by @edgedb/generate v0.5.4

import type {Executor} from "edgedb";

export type GetFtsQnasCountArgs = {
  readonly "query": string;
};

export type GetFtsQnasCountReturns = number;

export function getFtsQnasCount(client: Executor, args: GetFtsQnasCountArgs): Promise<GetFtsQnasCountReturns> {
  return client.queryRequiredSingle(`\
with res := (
  select fts::search(QNA, <str>$query, language := 'eng')
)
select count(res.object)`, args);

}
