// GENERATED by @edgedb/generate v0.5.4

import type {Executor} from "edgedb";

export type GetFtsDraftsArgs = {
  readonly "query": string;
  readonly "offset": number;
  readonly "limit": number;
};

export type GetFtsDraftsReturns = Array<{
  "id": string;
  "title": string | null;
  "question": string | null;
  "linkedTags": Array<{
    "name": string;
    "disabled": boolean | null;
  }>;
  "score": number;
}>;

export function getFtsDrafts(client: Executor, args: GetFtsDraftsArgs): Promise<GetFtsDraftsReturns> {
  return client.query(`\
with res := (
  select fts::search(QNADraft, <str>$query, language := 'eng')
)
select res.object {
  id, 
  title, 
  question,
  linkedTags: {
    name,
    disabled
  },
  score := res.score
} 
order by res.score desc
offset <int32>$offset
limit <int16>$limit;`, args);

}
