// GENERATED by @edgedb/generate v0.5.3

import type {Executor} from "edgedb";

export type GetFtsThreadsCountArgs = {
  readonly "query": string;
};

export type GetFtsThreadsCountReturns = number;

export function getFtsThreadsCount(client: Executor, args: GetFtsThreadsCountArgs): Promise<GetFtsThreadsCountReturns> {
  return client.queryRequiredSingle(`\
with res := (
  select fts::search(discord::Message, <str>$query, language := 'eng')
)
select count(
  distinct res.object.<messages[is Thread]
  filter not exists .draft and not exists .qna
)`, args);

}
