// GENERATED by @edgedb/generate v0.5.4

import type {Executor} from "edgedb";

export type GetFtsDraftsCountArgs = {
  readonly "query": string;
};

export type GetFtsDraftsCountReturns = number;

export function getFtsDraftsCount(client: Executor, args: GetFtsDraftsCountArgs): Promise<GetFtsDraftsCountReturns> {
  return client.queryRequiredSingle(`\
with res := (
  select fts::search(QNADraft, <str>$query, language := 'eng')
)
select count(res.object)`, args);

}
