// GENERATED by @edgedb/generate v0.5.4

import type {Executor} from "edgedb";


export type GetThreadsCountReturns = number;

export function getThreadsCount(client: Executor): Promise<GetThreadsCountReturns> {
  return client.queryRequiredSingle(`\
select count(
  discord::Thread
  filter not exists .draft and not exists .qna
)`);

}
