// GENERATED by @edgedb/generate v0.4.1

import type {Executor} from "edgedb";


export type GetHelpChannelsReturns = {
  "channel_id": string;
  "name": string;
}[];

export async function getHelpChannels(client: Executor): Promise<GetHelpChannelsReturns> {
  return client.query(`\
select discord::HelpChannel {
  channel_id,
  name
}`);

}
