// GENERATED by @edgedb/generate v0.5.4

import * as $ from "../reflection";
import * as _ from "../imports";
import type * as _std from "./std";
import type * as _default from "./default";
export type $HelpChannelλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "channel_id": $.PropertyDesc<_std.$str, $.Cardinality.One, true, false, false, false>;
  "name": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
}>;
type $HelpChannel = $.ObjectType<"discord::HelpChannel", $HelpChannelλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
  {channel_id: {__element__: _std.$str, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },},
]>;
const $HelpChannel = $.makeType<$HelpChannel>(_.spec, "f2cb6209-cb60-11ee-882f-138296cf37b2", _.syntax.literal);

const HelpChannel: $.$expr_PathNode<$.TypeSet<$HelpChannel, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($HelpChannel, $.Cardinality.Many), null);

export type $MessageλShape = $.typeutil.flatten<_default.$MessageλShape & {
  "message_id": $.PropertyDesc<_std.$str, $.Cardinality.One, true, false, false, false>;
}>;
type $Message = $.ObjectType<"discord::Message", $MessageλShape, null, [
  ..._default.$Message['__exclusives__'],
  {message_id: {__element__: _std.$str, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },},
]>;
const $Message = $.makeType<$Message>(_.spec, "f2b613f9-cb60-11ee-b24a-5f3874db40c4", _.syntax.literal);

const Message: $.$expr_PathNode<$.TypeSet<$Message, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Message, $.Cardinality.Many), null);

export type $ReviewCardλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "message_id": $.PropertyDesc<_std.$str, $.Cardinality.One, true, false, false, false>;
  "thread_id": $.PropertyDesc<_std.$str, $.Cardinality.One, true, false, false, false>;
  "<review_card[is discord::Thread]": $.LinkDesc<$Thread, $.Cardinality.Many, {}, false, false,  false, false>;
  "<review_card": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $ReviewCard = $.ObjectType<"discord::ReviewCard", $ReviewCardλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
  {message_id: {__element__: _std.$str, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },},
  {thread_id: {__element__: _std.$str, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },},
]>;
const $ReviewCard = $.makeType<$ReviewCard>(_.spec, "f2ba6363-cb60-11ee-86f8-f54b9c373ffc", _.syntax.literal);

const ReviewCard: $.$expr_PathNode<$.TypeSet<$ReviewCard, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($ReviewCard, $.Cardinality.Many), null);

export type $ThreadλShape = $.typeutil.flatten<_default.$ThreadλShape & {
  "review_card": $.LinkDesc<$ReviewCard, $.Cardinality.AtMostOne, {}, false, false,  false, false>;
  "suggested_by": $.LinkDesc<$User, $.Cardinality.Many, {}, false, false,  false, false>;
  "thread_id": $.PropertyDesc<_std.$str, $.Cardinality.One, true, false, false, false>;
}>;
type $Thread = $.ObjectType<"discord::Thread", $ThreadλShape, null, [
  ..._default.$Thread['__exclusives__'],
  {thread_id: {__element__: _std.$str, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },},
]>;
const $Thread = $.makeType<$Thread>(_.spec, "f2bc6ba8-cb60-11ee-bdd9-b361425a3c7a", _.syntax.literal);

const Thread: $.$expr_PathNode<$.TypeSet<$Thread, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Thread, $.Cardinality.Many), null);

export type $UserλShape = $.typeutil.flatten<_default.$UserλShape & {
  "<suggested_by[is discord::Thread]": $.LinkDesc<$Thread, $.Cardinality.Many, {}, false, false,  false, false>;
  "<suggested_by": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $User = $.ObjectType<"discord::User", $UserλShape, null, [
  ..._default.$User['__exclusives__'],
]>;
const $User = $.makeType<$User>(_.spec, "f2aedb74-cb60-11ee-952d-6bbb4de8e009", _.syntax.literal);

const User: $.$expr_PathNode<$.TypeSet<$User, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($User, $.Cardinality.Many), null);



export { $HelpChannel, HelpChannel, $Message, Message, $ReviewCard, ReviewCard, $Thread, Thread, $User, User };

type __defaultExports = {
  "HelpChannel": typeof HelpChannel;
  "Message": typeof Message;
  "ReviewCard": typeof ReviewCard;
  "Thread": typeof Thread;
  "User": typeof User
};
const __defaultExports: __defaultExports = {
  "HelpChannel": HelpChannel,
  "Message": Message,
  "ReviewCard": ReviewCard,
  "Thread": Thread,
  "User": User
};
export default __defaultExports;
