import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "./components/Header";
import "./globals.css";
import { getCurrentUser } from "./api/auth";
import { auth } from "./edgedb";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const links = [
  { href: "/", label: "HOME" },
  { href: "/threads", label: "THREADS" },
  { href: "/drafts", label: "DRAFTS" },
  { href: "/qnas", label: "QNAS" },
];

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = auth.getSession();

  const currentModerator = session.authToken
    ? await getCurrentUser(session.authToken)
    : null;

  const signoutUrl = auth.getSignoutUrl();

  return (
    <html lang="en">
      <body className={`${inter.className} px-6 pb-4 min-h-screen`}>
        {!currentModerator ? (
          <div className="min-h-screen flex justify-center items-center">
            <a href={auth.getOAuthUrl("builtin::oauth_discord")} className="">
              Sign In with Discord
            </a>
          </div>
        ) : (
          <div>
            <Header
              links={links.slice(1)}
              signoutUrl={signoutUrl}
              moderator={currentModerator.account.name}
            />

            {children}
          </div>
        )}
      </body>
    </html>
  );
}
