// GENERATED by @edgedb/generate v0.4.1

import type {Executor} from "edgedb";

export type AddHelpChannelArgs = {
  "channelId": string;
  "channelName": string;
};

export type AddHelpChannelReturns = {
  "id": string;
};

export async function addHelpChannel(client: Executor, args: AddHelpChannelArgs): Promise<AddHelpChannelReturns> {
  return client.queryRequiredSingle(`\
insert discord::HelpChannel {
  channel_id := <str>$channelId,
  name := <str>$channelName
}
unless conflict on .channel_id else (
  select discord::HelpChannel
)`, args);

}
