// GENERATED by @edgedb/generate v0.5.4

import type {Executor} from "edgedb";

export type AddHelpChannelArgs = {
  readonly "channelId": string;
  readonly "channelName": string;
};

export type AddHelpChannelReturns = {
  "id": string;
};

export function addHelpChannel(client: Executor, args: AddHelpChannelArgs): Promise<AddHelpChannelReturns> {
  return client.queryRequiredSingle(`\
insert discord::HelpChannel {
  channel_id := <str>$channelId,
  name := <str>$channelName
}
unless conflict on .channel_id else (
  select discord::HelpChannel
)`, args);

}
