// GENERATED by @edgedb/generate v0.5.3

import type {Executor} from "edgedb";

export type AddReviewCardArgs = {
  readonly "threadId": string;
  readonly "messageId": string;
  readonly "reviewThreadId": string;
};

export type AddReviewCardReturns = {
  "id": string;
} | null;

export function addReviewCard(client: Executor, args: AddReviewCardArgs): Promise<AddReviewCardReturns> {
  return client.querySingle(`\
with
  thread := (select discord::Thread filter .id = <uuid>$threadId)
update thread
set {
  review_card := (
    insert discord::ReviewCard {
      message_id := <str>$messageId,
      thread_id := <str>$reviewThreadId,
    }
  )
}`, args);

}
