// GENERATED by @edgedb/generate v0.5.3

import type {Executor} from "edgedb";


export type GetCurrentUserReturns = {
  "email": string;
  "account": {
    "name": string | null;
    "user_id": string;
  };
} | null;

export function getCurrentUser(client: Executor): Promise<GetCurrentUserReturns> {
  return client.querySingle(`\
select (global current_moderator) {
  email,
  account: {
    name, user_id
  }
}`);

}
