// GENERATED by @edgedb/generate v0.4.1

import type {Executor} from "edgedb";

export type IsHelpfulThreadArgs = {
  "threadId": string;
};

export type IsHelpfulThreadReturns = {
  "id": string;
} | null;

export async function isHelpfulThread(client: Executor, args: IsHelpfulThreadArgs): Promise<IsHelpfulThreadReturns> {
  return client.querySingle(`\
select discord::Thread
filter .thread_id = <str>$threadId`, args);

}
