// GENERATED by @edgedb/generate v0.4.1

import type {Executor} from "edgedb";

export type RemoveHelpChannelArgs = {
  "channelId": string;
};

export type RemoveHelpChannelReturns = {
  "id": string;
} | null;

export async function removeHelpChannel(client: Executor, args: RemoveHelpChannelArgs): Promise<RemoveHelpChannelReturns> {
  return client.querySingle(`\
delete discord::HelpChannel
filter .channel_id = <str>$channelId`, args);

}
