// GENERATED by @edgedb/generate v0.4.1

import type { Executor } from "edgedb";

export type SuggestThreadArgs = {
  messages: unknown;
  suggestorId: string;
  suggestorName: string;
  threadId: string;
  threadName: string;
};

export type SuggestThreadReturns = {
  id: string;
  title: string | null;
  thread_id: string;
  messages: {
    content: string;
    author: {
      name: string | null;
    };
    attachments: string[];
  }[];
  suggested_by: {
    name: string | null;
    user_id: string;
  }[];
};

export async function suggestThread(
  client: Executor,
  args: SuggestThreadArgs
): Promise<SuggestThreadReturns> {
  return client.queryRequiredSingle(
    `\
with
  messageContent := json_array_unpack(<json>$messages),
  authors := (
    id := <str>messageContent["author"]["id"],
    username := <str>messageContent["author"]["username"]
  ),

  users := (
    for user in (distinct ({
      authors,
      (id := <str>$suggestorId, username := <str>$suggestorName)
    }))
    union (
      insert discord::User {
        user_id := user.id,
        name := user.username,
      }
      unless conflict on .user_id else (
        select discord::User
      )
    )
  ),
  messages := (
    for message in messageContent
    union (
      insert discord::Message {
        message_id := <str>message["id"],
        content := <str>message["content"],
        attachments := array_agg(
          (for attachment in json_array_unpack(message["attachments"])
            union (
             select <str>attachment["url"]
            )
          )     
        ),
        author := (
          select users filter .user_id = <str>message["author"]["id"]
        )
      }
      unless conflict on .message_id else (select discord::Message)
    )
  ),
  suggested_by := (select users filter .user_id = <str>$suggestorId),
  thread := (insert discord::Thread {
    thread_id := <str>$threadId,
    title := <str>$threadName,
    messages := messages,
    suggested_by := suggested_by
  } unless conflict on .thread_id else (select discord::Thread))
select thread {
  id,
  title,
  thread_id, 
  messages: {
    content,
    author: {
      name,
    }
  },
  suggested_by: {
    name,
    user_id
  },
}`,
    args
  );
}
